In [1]:
import pandas as pd
import openpyxl

In [2]:
dados = {
    "nome": ["Ana", "Carlos", "Fernanda"],
    "nota": [8, 7, 10]
}

In [ ]:
df_alunos = pd.DataFrame(dados)

In [4]:
df_alunos

       nome  nota
0       Ana     8
1    Carlos     7
2  Fernanda    10

In [5]:
df_alunos.to_excel("alunos.xlsx", index=False)

In [6]:
df_lido = pd.read_excel("alunos.xlsx")

In [7]:
df_lido

       nome  nota
0       Ana     8
1    Carlos     7
2  Fernanda    10

In [8]:
print(df_lido.iloc[0])

nome    Ana
nota      8
Name: 0, dtype: object