### Importar Bases de Dados (Excel)
### Criar os DataFrames Referentes a Cada Base

In [2]:
import pandas as pd

In [3]:
# Importar Arquivos e Criar DataFrames

df_funcionarios = pd.read_excel('funcionarios.xlsx')
df_historico_salarios = pd.read_excel('historico_salarios.xlsx')
df_setores = pd.read_excel('setores.xlsx')

In [4]:
df_funcionarios.head()

   IdFuncionario     Nome  IdSetor  Salario  Idade
0              1      Ana        1     4500     25
1              2    Bruno        2     6000     30
2              3   Carlos        1     4800     28
3              4    Diana        3     7500     35
4              5  Eduardo        2     5200     40

### Exibir Nome e Salario da Base de Funcionários

In [5]:
print(df_funcionarios[["Nome", "Salario"]])

       Nome  Salario
0       Ana     4500
1     Bruno     6000
2    Carlos     4800
3     Diana     7500
4   Eduardo     5200
5  Fernanda     4000

### Filtrar Funcionários com Salários Acima de R$ 5.000

In [6]:
print(df_funcionarios[df_funcionarios["Salario"] > 5000])

   IdFuncionario     Nome  IdSetor  Salario  Idade
1              2    Bruno        2     6000     30
3              4    Diana        3     7500     35
4              5  Eduardo        2     5200     40

### Merge Entre Funcionários e Setores (Juntar Tabelas)

In [7]:
df_funcionarios_setor = df_funcionarios.merge(df_setores, on='IdSetor')

In [8]:
df_funcionarios_setor

   IdFuncionario      Nome  IdSetor  Salario  Idade             Setor
0              1       Ana        1     4500     25  Recursos Humanos
1              2     Bruno        2     6000     30        Tecnologia
2              3    Carlos        1     4800     28  Recursos Humanos
3              4     Diana        3     7500     35            Vendas
4              5   Eduardo        2     5200     40        Tecnologia
5              6  Fernanda        3     4000     26            Vendas

In [9]:
df_funcionarios_setor[["Nome", "Setor", "Salario"]]

       Nome             Setor  Salario
0       Ana  Recursos Humanos     4500
1     Bruno        Tecnologia     6000
2    Carlos  Recursos Humanos     4800
3     Diana            Vendas     7500
4   Eduardo        Tecnologia     5200
5  Fernanda            Vendas     4000

### Adicionar Novos Funcionários (Concat)

In [11]:
novos_funcionarios = {
    "IdFuncionario": [6, 7],
    "Nome": ["Gabriel", "Helena"],
    "IdSetor": [3, 4],
    "Salario": [4500, 5300],
    "Idade": [31, 38],
    }

df_novos_funcionarios = pd.DataFrame(novos_funcionarios)

In [12]:
df_novos_funcionarios

   IdFuncionario     Nome  IdSetor  Salario  Idade
0              6  Gabriel        3     4500     31
1              7   Helena        4     5300     38

In [ ]:
df_funcionarios = pd.concat([df_funcionarios, df_novos_funcionarios], ignore_index=True)

In [14]:
df_funcionarios

   IdFuncionario      Nome  IdSetor  Salario  Idade
0              1       Ana        1     4500     25
1              2     Bruno        2     6000     30
2              3    Carlos        1     4800     28
3              4     Diana        3     7500     35
4              5   Eduardo        2     5200     40
5              6  Fernanda        3     4000     26
0              6   Gabriel        3     4500     31
1              7    Helena        4     5300     38

### Agrupando Valores

01:51:26