### Pandas

In [1]:
import pandas as pd

In [2]:
df_funcionarios = pd.DataFrame({
    "Nome": ["Ana", "Carlos", "Maria"],
    "Salario": [3500.00, 4200.00, 5100.00],
    "Setor": ["RH", "TI", "Financeiro"]
})

print(df_funcionarios)

     Nome  Salario       Setor
0     Ana   3500.0          RH
1  Carlos   4200.0          TI
2   Maria   5100.0  Financeiro

In [3]:
df_funcionarios.head(1)  # Exibe as primeiras linhas do DataFrame

  Nome  Salario Setor
0  Ana   3500.0    RH

In [ ]:
df_funcionarios.tail(1)  # Exibe as últimas linhas do DataFrame

    Nome  Salario       Setor
2  Maria   5100.0  Financeiro

In [5]:
print(df_funcionarios.describe())  # Estatísticas descritivas do DataFrame

           Salario
count     3.000000
mean   4266.666667
std     802.080628
min    3500.000000
25%    3850.000000
50%    4200.000000
75%    4650.000000
max    5100.000000

In [6]:
print(df_funcionarios["Nome"])  # Acessa a coluna "Nome" do DataFrame

0       Ana
1    Carlos
2     Maria
Name: Nome, dtype: str

In [7]:
print(df_funcionarios[["Nome", "Salario"]])  # Acessa as colunas "Nome" e "Salario" do DataFrame

     Nome  Salario
0     Ana   3500.0
1  Carlos   4200.0
2   Maria   5100.0

In [8]:
print(df_funcionarios[df_funcionarios["Salario"] > 4000])  # Filtra funcionários com salário maior que 4000

     Nome  Salario       Setor
1  Carlos   4200.0          TI
2   Maria   5100.0  Financeiro

In [9]:
print(df_funcionarios[df_funcionarios["Salario"] > 4000]["Nome"])  # Filtra e exibe apenas os nomes dos funcionários com salário maior que 4000

1    Carlos
2     Maria
Name: Nome, dtype: str

In [11]:
resultado = df_funcionarios[(df_funcionarios["Salario"] > 4000) & 
                            (df_funcionarios["Setor"] == "TI")][["Nome", "Salario", "Setor"]]  # Filtra funcionários com salário maior que 4000 e setor "TI"

In [12]:
resultado

     Nome  Salario Setor
1  Carlos   4200.0    TI

### Numpy

In [13]:
import numpy as np

In [18]:
notas = np.array([7.5, 8.0, 6.5, 9.0, 5.0])

In [19]:
print("Notas:", notas)

Notas: [7.5 8.  6.5 9.  5. ]

In [20]:
print("Média: ", np.mean(notas))  # Calcula a média das notas
print("Maior: ", np.max(notas))  # Calcula o valor máximo das notas
print("Mínimo: ", np.min(notas))  # Calcula o valor mínimo das notas

Média:  7.2
Maior:  9.0
Mínimo:  5.0

In [21]:
print("+ 1 ponto", notas + 1)  # Adiciona 1 ponto a cada nota

+ 1 ponto [ 8.5  9.   7.5 10.   6. ]

In [22]:
print("Aprovados:", notas >= 7)  # Filtra e exibe apenas as notas aprovadas (maiores ou iguais a 7)

Aprovados: [ True  True False  True False]

In [23]:
print("Notas Aprovadas: ", notas[notas >= 7])  # Exibe apenas as notas aprovadas (maiores ou iguais a 7)

Notas Aprovadas:  [7.5 8.  9. ]

In [25]:
print("Soma: ", np.sum(notas))  # Calcula a soma de todas as notas

Soma:  36.0