In [2]:
import pandas as pd

In [3]:
dados = {
    "Produto": ["Notebook", "Mouse", "Teclado", "Monitor"],
    "Quantidade": [2, 5, 3, 1],
    "Valor": [3500.00, 80.00, 150.00, 1200.00]
}

In [4]:
df = pd.DataFrame(dados)

In [5]:
df

    Produto  Quantidade   Valor
0  Notebook           2  3500.0
1     Mouse           5    80.0
2   Teclado           3   150.0
3   Monitor           1  1200.0

In [7]:
print("Valor: ")
print(df["Valor"])
print()
print(type(df["Valor"]))

Valor:
0    3500.0
1      80.0
2     150.0
3    1200.0
Name: Valor, dtype: float64

<class 'pandas.Series'>

In [8]:
print(df[["Produto", "Valor"]])

    Produto   Valor
0  Notebook  3500.0
1     Mouse    80.0
2   Teclado   150.0
3   Monitor  1200.0

In [9]:
# Filtrando Valores

print(df[df["Valor"] > 200])

    Produto  Quantidade   Valor
0  Notebook           2  3500.0
3   Monitor           1  1200.0

In [ ]:
# Filtrando Valores e Selecionando Colunas

print(df[df["Valor"] >= 150][["Produto", "Valor"]])

    Produto   Valor
0  Notebook  3500.0
2   Teclado   150.0
3   Monitor  1200.0

In [11]:
# Criando uma Nova Coluna com Base nas Informações de Quantidade e Valor

df["Total"] = df["Quantidade"] * df["Valor"]

In [12]:
df

    Produto  Quantidade   Valor   Total
0  Notebook           2  3500.0  7000.0
1     Mouse           5    80.0   400.0
2   Teclado           3   150.0   450.0
3   Monitor           1  1200.0  1200.0

In [13]:
# Média de Valor

print(df["Valor"].mean())

1232.5

In [14]:
# Máximo e Mínimo

print(df["Valor"].max())
print(df["Valor"].min())

3500.0
80.0

In [16]:
# Contagem

print(df["Produto"].count())

4

In [19]:
# Exibir Primeiras Linhas

print(df.head(2))

    Produto  Quantidade   Valor   Total
0  Notebook           2  3500.0  7000.0
1     Mouse           5    80.0   400.0

In [20]:
# Exibir Últimas Linhas

print(df.tail(2))

   Produto  Quantidade   Valor   Total
2  Teclado           3   150.0   450.0
3  Monitor           1  1200.0  1200.0

In [ ]:
print(df.shape) # Exibe Linhas e Colunas Respectivamente

(4, 4)

In [22]:
print(df.columns)

Index(['Produto', 'Quantidade', 'Valor', 'Total'], dtype='str')

In [24]:
print(df.sort_values("Valor", ascending=False))

    Produto  Quantidade   Valor   Total
0  Notebook           2  3500.0  7000.0
3   Monitor           1  1200.0  1200.0
2   Teclado           3   150.0   450.0
1     Mouse           5    80.0   400.0