In [21]:
import re # expressões regulares REGEX
import pandas as pd

In [22]:
dados = {"nome": ["Ana", "Carlos", "Maria", "José"],
        "telefone":["(47) 99999-1111", "47 98888-2222", "+55 (47) 97777-3333", "47966664444"]}

In [23]:
df = pd.DataFrame(dados)

In [24]:
df

     nome             telefone
0     Ana      (47) 99999-1111
1  Carlos        47 98888-2222
2   Maria  +55 (47) 97777-3333
3    José          47966664444

In [25]:
df_copy = df

In [26]:
df["telefone"] = df["telefone"].apply(lambda x: re.sub(r"\D", "", x))

In [27]:
df["telefone"] = df["telefone"].apply(lambda x: re.sub(r"[^0-9]", "", x))

In [28]:
df

     nome       telefone
0     Ana    47999991111
1  Carlos    47988882222
2   Maria  5547977773333
3    José    47966664444

In [29]:
df_copy

     nome       telefone
0     Ana    47999991111
1  Carlos    47988882222
2   Maria  5547977773333
3    José    47966664444